using System.Collections.Generic;

namespace BelievableBioenergy
{

    class ModPlantValues
    {

        public const float purpleVegetableYield = 6f;
        public const float hangingFruitYield = 100f;
        public const float bulboTreeYield = 10f;

        public static TechType GetFruit(TechType seed) => seedToFruit.GetOrDefault(seed, seed);

        public static bool IsSeed(TechType techType)
        {
            string name = System.Enum.GetName(typeof(TechType), techType);                
            return name.EndsWith("Seed") || name.EndsWith("Spore") || techType == TechType.PurpleVegetable || techType == TechType.BloodOil || techType == TechType.HangingFruit || techType == TechType.BulboTreePiece;
        }
            
        public static readonly Dictionary<TechType, TechType> seedToFruit = new Dictionary<TechType, TechType>(TechTypeExtensions.sTechTypeComparer)
        {
            {TechType.MelonSeed, TechType.Melon},
            {TechType.PinkMushroomSpore, TechType.PinkMushroom }
        };

        public static readonly Dictionary<TechType, float> charge = new Dictionary<TechType, float>(TechTypeExtensions.sTechTypeComparer)
    {
        {
            TechType.Melon,
            5f
        },
        {
            TechType.PurpleVegetable,
            6f
        },
        {
            TechType.HangingFruit,
            0.1f
        },
        {
            TechType.SmallMelon,
            3f
        },
        {
            TechType.JellyPlant,
            24f
        },
        {
            TechType.BulboTreePiece,
            2f
        },
        {
            TechType.KooshChunk,
            42f
        },
        {
            TechType.CreepvinePiece,
            21f
        },
        {
            TechType.WhiteMushroom,
            21f
        },
        {
            TechType.AcidMushroom,
            21f
        },
        {
            TechType.SmallFan,
            7f
        },
        {
            TechType.PurpleRattle,
            14f
        },
        {
            TechType.PinkMushroom,
            10f
        },
        {
            TechType.BloodVine,
            7f
        },
        {
            TechType.BluePalm,
            7f
        },
        {
            TechType.BulboTree,
            7f
        },
        {
            TechType.Creepvine,
            7f
        },
        {
            TechType.EyesPlant,
            7f
        },
        {
            TechType.FernPalm,
            7f
        },
        {
            TechType.GabeSFeather,
            7f
        },
        {
            TechType.HangingFruitTree,
            7f
        },
        {
            TechType.SmallKoosh,
            7f
        },
        {
            TechType.MembrainTree,
            7f
        },
        {
            TechType.OrangeMushroom,
            7f
        },
        {
            TechType.OrangePetalsPlant,
            14f
        },
        {
            TechType.PinkFlower,
            7f
        },
        {
            TechType.PurpleBrainCoral,
            7f
        },
        {
            TechType.PurpleBranches,
            7f
        },
        {
            TechType.PurpleFan,
            7f
        },
        {
            TechType.PurpleStalk,
            7f
        },
        {
            TechType.PurpleTentacle,
            7f
        },
        {
            TechType.PurpleVasePlant,
            7f
        },
        {
            TechType.PurpleVegetablePlant,
            7f
        },
        {
            TechType.RedBasketPlant,
            7f
        },
        {
            TechType.RedBush,
            7f
        },
        {
            TechType.RedConePlant,
            7f
        },
        {
            TechType.RedGreenTentacle,
            7f
        },
        {
            TechType.RedRollPlant,
            7f
        },
        {
            TechType.SeaCrown,
            7f
        },
        {
            TechType.ShellGrass,
            7f
        },
        {
            TechType.SnakeMushroom,
            7f
        },
        {
            TechType.SpikePlant,
            7f
        },
        {
            TechType.SpottedLeavesPlant,
            7f
        },
        {
            TechType.JeweledDiskPiece,
            7f
        },
        {
            TechType.CoralChunk,
            7f
        },
        {
            TechType.StalkerTooth,
            7f
        },
        {
            TechType.TreeMushroomPiece,
            7f
        },
        {
            TechType.OrangeMushroomSpore,
            14f
        },
        {
            TechType.PurpleVasePlantSeed,
            14f
        },
        {
            TechType.AcidMushroomSpore,
            2f
        },
        {
            TechType.WhiteMushroomSpore,
            2f
        },
        {
            TechType.PinkMushroomSpore,
            1f
        },
        {
            TechType.PurpleRattleSpore,
            1f
        },
        {
            TechType.MelonSeed,
            1f
        },
        {
            TechType.PurpleBrainCoralPiece,
            7f
        },
        {
            TechType.SpikePlantSeed,
            7f
        },
        {
            TechType.BluePalmSeed,
            7f
        },
        {
            TechType.PurpleFanSeed,
            2f
        },
        {
            TechType.SmallFanSeed,
            3f
        },
        {
            TechType.PurpleTentacleSeed,
            7f
        },
        {
            TechType.JellyPlantSeed,
            1f
        },
        {
            TechType.GabeSFeatherSeed,
            7f
        },
        {
            TechType.SeaCrownSeed,
            7f
        },
        {
            TechType.MembrainTreeSeed,
            7f
        },
        {
            TechType.PinkFlowerSeed,
            1f
        },
        {
            TechType.FernPalmSeed,
            7f
        },
        {
            TechType.OrangePetalsPlantSeed,
            10f
        },
        {
            TechType.EyesPlantSeed,
            7f
        },
        {
            TechType.RedGreenTentacleSeed,
            7f
        },
        {
            TechType.PurpleStalkSeed,
            7f
        },
        {
            TechType.RedBasketPlantSeed,
            7f
        },
        {
            TechType.RedBushSeed,
            7f
        },
        {
            TechType.RedConePlantSeed,
            7f
        },
        {
            TechType.SpottedLeavesPlantSeed,
            7f
        },
        {
            TechType.RedRollPlantSeed,
            7f
        },
        {
            TechType.PurpleBranchesSeed,
            7f
        },
        {
            TechType.SnakeMushroomSpore,
            14f
        },
        {
            TechType.CreepvineSeedCluster,
            14f
        },
        {
            TechType.BloodOil,
            42f
        },
        {
            TechType.Bladderfish,
            21f
        },
        {
            TechType.Boomerang,
            28f
        },
        {
            TechType.LavaBoomerang,
            28f
        },
        {
            TechType.Eyeye,
            42f
        },
        {
            TechType.LavaEyeye,
            42f
        },
        {
            TechType.GarryFish,
            42f
        },
        {
            TechType.HoleFish,
            28f
        },
        {
            TechType.Hoopfish,
            21f
        },
        {
            TechType.Spinefish,
            21f
        },
        {
            TechType.Hoverfish,
            35f
        },
        {
            TechType.Oculus,
            63f
        },
        {
            TechType.Peeper,
            42f
        },
        {
            TechType.Reginald,
            49f
        },
        {
            TechType.Spadefish,
            42f
        },
        {
            TechType.CookedBladderfish,
            15f
        },
        {
            TechType.CookedBoomerang,
            21f
        },
        {
            TechType.CookedLavaBoomerang,
            21f
        },
        {
            TechType.CookedEyeye,
            31f
        },
        {
            TechType.CookedLavaEyeye,
            31f
        },
        {
            TechType.CookedGarryFish,
            24f
        },
        {
            TechType.CookedHoleFish,
            21f
        },
        {
            TechType.CookedHoopfish,
            15f
        },
        {
            TechType.CookedSpinefish,
            15f
        },
        {
            TechType.CookedHoverfish,
            26f
        },
        {
            TechType.CookedOculus,
            47f
        },
        {
            TechType.CookedPeeper,
            31f
        },
        {
            TechType.CookedReginald,
            36f
        },
        {
            TechType.CookedSpadefish,
            31f
        },
        {
            TechType.CuredBladderfish,
            11f
        },
        {
            TechType.CuredBoomerang,
            15f
        },
        {
            TechType.CuredLavaBoomerang,
            15f
        },
        {
            TechType.CuredEyeye,
            24f
        },
        {
            TechType.CuredLavaEyeye,
            24f
        },
        {
            TechType.CuredGarryFish,
            18f
        },
        {
            TechType.CuredHoleFish,
            15f
        },
        {
            TechType.CuredHoopfish,
            11f
        },
        {
            TechType.CuredSpinefish,
            11f
        },
        {
            TechType.CuredHoverfish,
            19f
        },
        {
            TechType.CuredOculus,
            35f
        },
        {
            TechType.CuredPeeper,
            23f
        },
        {
            TechType.CuredReginald,
            27f
        },
        {
            TechType.CuredSpadefish,
            23f
        },
        {
            TechType.Jumper,
            28f
        },
        {
            TechType.RabbitRay,
            42f
        },
        {
            TechType.Stalker,
            56f
        },
        {
            TechType.Jellyray,
            35f
        },
        {
            TechType.Gasopod,
            70f
        },
        {
            TechType.Sandshark,
            63f
        },
        {
            TechType.BoneShark,
            63f
        },
        {
            TechType.CrabSquid,
            77f
        },
        {
            TechType.Mesmer,
            56f
        },
        {
            TechType.Biter,
            14f
        },
        {
            TechType.Crabsnake,
            70f
        },
        {
            TechType.Shocker,
            77f
        },
        {
            TechType.Shuttlebug,
            28f
        },
        {
            TechType.LavaLizard,
            56f
        },
        {
            TechType.Reefback,
            84f
        },
        {
            TechType.Crash,
            56f
        },
        {
            TechType.SafeShallowsEgg,
            35f
        },
        {
            TechType.KelpForestEgg,
            35f
        },
        {
            TechType.GrassyPlateausEgg,
            35f
        },
        {
            TechType.GrandReefsEgg,
            35f
        },
        {
            TechType.MushroomForestEgg,
            35f
        },
        {
            TechType.KooshZoneEgg,
            35f
        },
        {
            TechType.TwistyBridgesEgg,
            35f
        },
        {
            TechType.StalkerEgg,
            10f
        },
        {
            TechType.StalkerEggUndiscovered,
            10f
        },
        {
            TechType.ReefbackEgg,
            28f
        },
        {
            TechType.ReefbackEggUndiscovered,
            28f
        },
        {
            TechType.SpadefishEgg,
            14f
        },
        {
            TechType.SpadefishEggUndiscovered,
            14f
        },
        {
            TechType.RabbitrayEgg,
            14f
        },
        {
            TechType.RabbitrayEggUndiscovered,
            14f
        },
        {
            TechType.MesmerEgg,
            17f
        },
        {
            TechType.MesmerEggUndiscovered,
            17f
        },
        {
            TechType.JumperEgg,
            10f
        },
        {
            TechType.JumperEggUndiscovered,
            10f
        },
        {
            TechType.SandsharkEgg,
            21f
        },
        {
            TechType.SandsharkEggUndiscovered,
            21f
        },
        {
            TechType.JellyrayEgg,
            11f
        },
        {
            TechType.JellyrayEggUndiscovered,
            11f
        },
        {
            TechType.BonesharkEgg,
            21f
        },
        {
            TechType.BonesharkEggUndiscovered,
            21f
        },
        {
            TechType.CrabsnakeEgg,
            23f
        },
        {
            TechType.CrabsnakeEggUndiscovered,
            23f
        },
        {
            TechType.ShockerEgg,
            25f
        },
        {
            TechType.ShockerEggUndiscovered,
            25f
        },
        {
            TechType.GasopodEgg,
            23f
        },
        {
            TechType.GasopodEggUndiscovered,
            23f
        },
        {
            TechType.CrashEgg,
            18f
        },
        {
            TechType.CrashEggUndiscovered,
            18f
        },
        {
            TechType.CutefishEgg,
            21f
        },
        {
            TechType.CutefishEggUndiscovered,
            21f
        },
        {
            TechType.CrabsquidEgg,
            25f
        },
        {
            TechType.CrabsquidEggUndiscovered,
            25f
        },
        {
            TechType.LavaLizardEgg,
            18f
        },
        {
            TechType.LavaLizardEggUndiscovered,
            18f
        },
        {
            TechType.Floater,
            5f
        },
        {
            TechType.Lubricant,
            2f
        },
        {
            TechType.SeaTreaderPoop,
            200f
        }
    };
    }
}